# Generated by Django 5.0.1 on 2024-01-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('semester', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('weight', models.FloatField()),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.assignmenttype')),
            ],
        ),
        migrations.AddField(
            model_name='assignmenttype',
            name='class_associated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_types', to='classes.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='classes', to='classes.user'),
        ),
    ]
