# Generated by Django 5.0.1 on 2024-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttype',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
