# Generated by Django 5.0.1 on 2024-01-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_assignment_max_score_alter_assignmenttype_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
