# Generated by Django 5.0.1 on 2024-01-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_assignment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='DEFAULT NAME', max_length=200),
            preserve_default=False,
        ),
    ]
