# Generated by Django 5.0.1 on 2024-01-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttype',
            name='default_name',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
    ]
