# Generated by Django 5.0.1 on 2024-01-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_assignmenttype_lock_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttype',
            name='max_score',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
