# Generated by Django 5.0.1 on 2024-01-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_assignmenttype_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='desired_score',
            field=models.FloatField(default=100.0),
        ),
    ]
