# Generated by Django 5.0.1 on 2024-01-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_class_desired_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='users',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='classes.user')),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='classes.semester'),
        ),
    ]
