# Generated by Django 5.0.1 on 2024-01-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_remove_class_users_alter_class_name_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
        migrations.AddField(
            model_name='semester',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='Summer', max_length=7),
            preserve_default=False,
        ),
    ]
