# Generated by Django 5.0.1 on 2024-01-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_remove_semester_name_semester_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='units',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=7),
        ),
    ]
