# Generated by Django 5.0.1 on 2024-01-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_class_units_alter_semester_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='units',
            field=models.IntegerField(verbose_name='Units/Credits'),
        ),
    ]
