# Generated by Django 5.0.1 on 2024-01-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_class_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttype',
            name='max_score',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
    ]
