# Generated by Django 5.0.1 on 2024-01-11 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_alter_assignmenttype_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='classes.semester'),
        ),
    ]
